"""authentication core

Revision ID: 0015_authentication_core
Revises: 0014_deal_storage_sqlalchemy
Create Date: 2026-07-15
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0015_authentication_core"
down_revision = "0014_deal_storage_sqlalchemy"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "auth_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text(
                "gen_random_uuid()"
            ),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column(
            "device_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoke_reason",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_auth_sessions_user_id",
        "auth_sessions",
        ["user_id"],
    )

    op.create_table(
        "auth_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text(
                "gen_random_uuid()"
            ),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "auth_sessions.id",
                ondelete="CASCADE",
            ),
            nullable=True,
        ),
        sa.Column(
            "purpose",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "token_hash",
            sa.String(length=128),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "family_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "parent_token_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "auth_tokens.id",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "consumed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text(
                "'{}'::jsonb"
            ),
        ),
    )
    op.create_index(
        "ix_auth_tokens_user_id",
        "auth_tokens",
        ["user_id"],
    )
    op.create_index(
        "ix_auth_tokens_session_id",
        "auth_tokens",
        ["session_id"],
    )
    op.create_index(
        "ix_auth_tokens_purpose",
        "auth_tokens",
        ["purpose"],
    )
    op.create_index(
        "ix_auth_tokens_family_id",
        "auth_tokens",
        ["family_id"],
    )
    op.create_index(
        "ix_auth_tokens_active_family",
        "auth_tokens",
        [
            "family_id",
            "purpose",
            "revoked_at",
        ],
    )

    op.create_table(
        "auth_login_attempts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text(
                "gen_random_uuid()"
            ),
        ),
        sa.Column(
            "normalized_identifier",
            sa.String(length=320),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=True,
        ),
        sa.Column(
            "succeeded",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "failure_reason",
            sa.String(length=128),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_auth_login_attempts_identifier",
        "auth_login_attempts",
        ["normalized_identifier"],
    )
    op.create_index(
        "ix_auth_login_attempts_attempted_at",
        "auth_login_attempts",
        ["attempted_at"],
    )
    op.create_index(
        "ix_auth_login_attempts_identifier_time",
        "auth_login_attempts",
        [
            "normalized_identifier",
            "attempted_at",
        ],
    )

    op.create_table(
        "auth_account_security",
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            primary_key=True,
        ),
        sa.Column(
            "failed_login_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "email_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "security_version",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        "auth_password_history",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text(
                "gen_random_uuid()"
            ),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "password_hash",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_auth_password_history_user_id",
        "auth_password_history",
        ["user_id"],
    )

    op.create_table(
        "auth_audit_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text(
                "gen_random_uuid()"
            ),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "auth_sessions.id",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "event_type",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "correlation_id",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text(
                "'{}'::jsonb"
            ),
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_auth_audit_events_user_id",
        "auth_audit_events",
        ["user_id"],
    )
    op.create_index(
        "ix_auth_audit_events_session_id",
        "auth_audit_events",
        ["session_id"],
    )
    op.create_index(
        "ix_auth_audit_events_event_type",
        "auth_audit_events",
        ["event_type"],
    )
    op.create_index(
        "ix_auth_audit_events_occurred_at",
        "auth_audit_events",
        ["occurred_at"],
    )


def downgrade() -> None:
    op.drop_table("auth_audit_events")
    op.drop_table("auth_password_history")
    op.drop_table("auth_account_security")
    op.drop_table("auth_login_attempts")
    op.drop_table("auth_tokens")
    op.drop_table("auth_sessions")
